# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H3W4csgLqPG4doEcq4gkN2y-oCLc9uLH
"""

list=[2,4,6,8,10]

square=[i**2 for i in list]
print('square of numbers:',square)

cube=[i**3 for i in list]
print('cube of numbers:',cube)

